
const List<Country> countries = [
  Country(
    name: "Afghanistan",
    flag: "af",
    code: "AF",
    dialCode: "+93",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Åland Islands",
    flag: "🇦🇽",
    code: "AX",
    dialCode: "+358",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Albania",
    flag: "al",
    code: "AL",
    dialCode: "+355",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Algeria",
    flag: "dz",
    code: "DZ",
    dialCode: "+213",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "American Samoa",
    flag: "as",
    code: "AS",
    dialCode: "+1684",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Andorra",
    flag: "ad",
    code: "AD",
    dialCode: "+376",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Angola",
    flag: "ao",
    code: "AO",
    dialCode: "+244",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Anguilla",
    flag: "ai",
    code: "AI",
    dialCode: "+1264",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Antarctica",
    flag: "🇦🇶",
    code: "AQ",
    dialCode: "+672",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Antigua and Barbuda",
    flag: "ag",
    code: "AG",
    dialCode: "+1268",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Argentina",
    flag: "ar",
    code: "AR",
    dialCode: "+54",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Armenia",
    flag: "am",
    code: "AM",
    dialCode: "+374",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Aruba",
    flag: "aw",
    code: "AW",
    dialCode: "+297",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Australia",
    flag: "au",
    code: "AU",
    dialCode: "+61",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Austria",
    flag: "at",
    code: "AT",
    dialCode: "+43",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: "Azerbaijan",
    flag: "az",
    code: "AZ",
    dialCode: "+994",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Bahamas",
    flag: "bs",
    code: "BS",
    dialCode: "+1242",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Bahrain",
    flag: "bh",
    code: "BH",
    dialCode: "+973",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bangladesh",
    flag: "bd",
    code: "BD",
    dialCode: "+880",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Barbados",
    flag: "bb",
    code: "BB",
    dialCode: "+1246",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Belarus",
    flag: "by",
    code: "BY",
    dialCode: "+375",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Belgium",
    flag: "be",
    code: "BE",
    dialCode: "+32",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Belize",
    flag: "bz",
    code: "BZ",
    dialCode: "+501",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Benin",
    flag: "bj",
    code: "BJ",
    dialCode: "+229",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bermuda",
    flag: "bm",
    code: "BM",
    dialCode: "+1441",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Bhutan",
    flag: "bt",
    code: "BT",
    dialCode: "+975",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bolivia, Plurinational State of bolivia",
    flag: "bo",
    code: "BO",
    dialCode: "+591",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bosnia and Herzegovina",
    flag: "ba",
    code: "BA",
    dialCode: "+387",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Botswana",
    flag: "bw",
    code: "BW",
    dialCode: "+267",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Bouvet Island",
    flag: "🇧🇻",
    code: "BV",
    dialCode: "+47",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Brazil",
    flag: "br",
    code: "BR",
    dialCode: "+55",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "British Indian Ocean Territory",
    flag: "io",
    code: "IO",
    dialCode: "+246",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Brunei Darussalam",
    flag: "bn",
    code: "BN",
    dialCode: "+673",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Bulgaria",
    flag: "bg",
    code: "BG",
    dialCode: "+359",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Burkina Faso",
    flag: "bf",
    code: "BF",
    dialCode: "+226",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Burundi",
    flag: "bi",
    code: "BI",
    dialCode: "+257",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Cambodia",
    flag: "kh",
    code: "KH",
    dialCode: "+855",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Cameroon",
    flag: "cm",
    code: "CM",
    dialCode: "+237",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Campione d'Italia",
    flag: "🇮🇹",
    code: "IT",
    dialCode: "+41",
    regionCode: "91",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: "Canada",
    flag: "ca",
    code: "CA",
    dialCode: "+1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Cape Verde",
    flag: "cv",
    code: "CV",
    dialCode: "+238",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Cayman Islands",
    flag: "ky",
    code: "KY",
    dialCode: "+345",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Central African Republic",
    flag: "cf",
    code: "CF",
    dialCode: "+236",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Chad",
    flag: "td",
    code: "TD",
    dialCode: "+235",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Chile",
    flag: "cl",
    code: "CL",
    dialCode: "+56",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "China",
    flag: "cn",
    code: "CN",
    dialCode: "+86",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Christmas Island",
    flag: "cx",
    code: "CX",
    dialCode: "+61",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Cocos (Keeling) Islands",
    flag: "cc",
    code: "CC",
    dialCode: "+61",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Colombia",
    flag: "co",
    code: "CO",
    dialCode: "+57",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Comoros",
    flag: "km",
    code: "KM",
    dialCode: "+269",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Congo",
    flag: "cg",
    code: "CG",
    dialCode: "+242",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Congo, The Democratic Republic of the Congo",
    flag: "cd",
    code: "CD",
    dialCode: "+243",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Cook Islands",
    flag: "ck",
    code: "CK",
    dialCode: "+682",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Costa Rica",
    flag: "cr",
    code: "CR",
    dialCode: "+506",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    code: "CI",
    dialCode: "+225",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Croatia",
    flag: "hr",
    code: "HR",
    dialCode: "+385",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Cuba",
    flag: "cu",
    code: "CU",
    dialCode: "+53",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Cyprus",
    flag: "cy",
    code: "CY",
    dialCode: "+357",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Czech Republic",
    flag: "cz",
    code: "CZ",
    dialCode: "+420",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Denmark",
    flag: "dk",
    code: "DK",
    dialCode: "+45",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Djibouti",
    flag: "dj",
    code: "DJ",
    dialCode: "+253",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Dominica",
    flag: "dm",
    code: "DM",
    dialCode: "+1767",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Dominican Republic",
    flag: "do",
    code: "DO",
    dialCode: "+1849",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Ecuador",
    flag: "ec",
    code: "EC",
    dialCode: "+593",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: "Egypt",
    flag: "eg",
    code: "EG",
    dialCode: "+20",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "El Salvador",
    flag: "sv",
    code: "SV",
    dialCode: "+503",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Equatorial Guinea",
    flag: "gq",
    code: "GQ",
    dialCode: "+240",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Eritrea",
    flag: "er",
    code: "ER",
    dialCode: "+291",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Estonia",
    flag: "ee",
    code: "EE",
    dialCode: "+372",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Ethiopia",
    flag: "et",
    code: "ET",
    dialCode: "+251",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Falkland Islands (Malvinas)",
    flag: "fk",
    code: "FK",
    dialCode: "+500",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Faroe Islands",
    flag: "🇫🇴",
    code: "FO",
    dialCode: "+298",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Fiji",
    flag: "fj",
    code: "FJ",
    dialCode: "+679",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Finland",
    flag: "fi",
    code: "FI",
    dialCode: "+358",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "France",
    flag: "fr",
    code: "FR",
    dialCode: "+33",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "French Guiana",
    flag: "🇬🇫",
    code: "GF",
    dialCode: "+594",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "French Polynesia",
    flag: "pf",
    code: "PF",
    dialCode: "+689",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "French Southern Territories",
    flag: "🇹🇫",
    code: "TF",
    dialCode: "+262",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Gabon",
    flag: "ga",
    code: "GA",
    dialCode: "+241",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Gambia",
    flag: "gm",
    code: "GM",
    dialCode: "+220",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Georgia",
    flag: "🇬🇪",
    code: "GE",
    dialCode: "+995",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: "Germany",
    flag: "de",
    code: "DE",
    dialCode: "+49",
    minLength: 9,
    maxLength: 13,
  ),
  Country(
    name: "Ghana",
    flag: "gh",
    code: "GH",
    dialCode: "+233",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Gibraltar",
    flag: "gi",
    code: "GI",
    dialCode: "+350",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Greece",
    flag: "gr",
    code: "GR",
    dialCode: "+30",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Greenland",
    flag: "gl",
    code: "GL",
    dialCode: "+299",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Grenada",
    flag: "gd",
    code: "GD",
    dialCode: "+1473",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Guadeloupe",
    flag: "🇬🇵",
    code: "GP",
    dialCode: "+590",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Guam",
    flag: "gu",
    code: "GU",
    dialCode: "+1671",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Guatemala",
    flag: "gt",
    code: "GT",
    dialCode: "+502",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Guernsey",
    flag: "gg",
    code: "GG",
    dialCode: "+44",
    regionCode: "1481",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Guinea",
    flag: "gn",
    code: "GN",
    dialCode: "+224",
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    name: "Guinea-Bissau",
    flag: "gw",
    code: "GW",
    dialCode: "+245",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Guyana",
    flag: "🇬🇾",
    code: "GY",
    dialCode: "+592",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Haiti",
    flag: "ht",
    code: "HT",
    dialCode: "+509",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    code: "HM",
    dialCode: "+672",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Holy See (Vatican City State)",
    flag: "va",
    code: "VA",
    dialCode: "+379",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Honduras",
    flag: "hn",
    code: "HN",
    dialCode: "+504",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Hong Kong",
    flag: "hk",
    code: "HK",
    dialCode: "+852",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Hungary",
    flag: "hu",
    code: "HU",
    dialCode: "+36",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Iceland",
    flag: "is",
    code: "IS",
    dialCode: "+354",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "India",
    flag: "in",
    code: "IN",
    dialCode: "+91",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Indonesia",
    flag: "id",
    code: "ID",
    dialCode: "+62",
    minLength: 10,
    maxLength: 13,
  ),
  Country(
    name: "Iran, Islamic Republic of Persian Gulf",
    flag: "ir",
    code: "IR",
    dialCode: "+98",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Iraq",
    flag: "iq",
    code: "IQ",
    dialCode: "+964",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Ireland",
    flag: "ie",
    code: "IE",
    dialCode: "+353",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "Isle of Man",
    flag: "im",
    code: "IM",
    dialCode: "+44",
    regionCode: "1624",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Israel",
    flag: "il",
    code: "IL",
    dialCode: "+972",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Italy",
    flag: "it",
    code: "IT",
    dialCode: "+39",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: "Jamaica",
    flag: "jm",
    code: "JM",
    dialCode: "+1876",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Japan",
    flag: "jp",
    code: "JP",
    dialCode: "+81",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Jersey",
    flag: "je",
    code: "JE",
    dialCode: "+44",
    regionCode: "1534",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Jordan",
    flag: "jo",
    code: "JO",
    dialCode: "+962",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Kazakhstan",
    flag: "kz",
    code: "KZ",
    dialCode: "+7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Kenya",
    flag: "ke",
    code: "KE",
    dialCode: "+254",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Kiribati",
    flag: "ki",
    code: "KI",
    dialCode: "+686",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Korea, Democratic People's Republic of Korea",
    flag: "kp",
    code: "KP",
    dialCode: "+850",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Korea, Republic of South Korea",
    flag: "kr",
    code: "KR",
    dialCode: "+82",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Kosovo",
    flag: "xk",
    code: "XK",
    dialCode: "+383",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Kuwait",
    flag: "kw",
    code: "KW",
    dialCode: "+965",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Kyrgyzstan",
    flag: "kg",
    code: "KG",
    dialCode: "+996",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Laos",
    flag: "la",
    code: "LA",
    dialCode: "+856",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Latvia",
    flag: "lv",
    code: "LV",
    dialCode: "+371",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Lebanon",
    flag: "lb",
    code: "LB",
    dialCode: "+961",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Lesotho",
    flag: "ls",
    code: "LS",
    dialCode: "+266",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Liberia",
    flag: "lr",
    code: "LR",
    dialCode: "+231",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Libyan Arab Jamahiriya",
    flag: "ly",
    code: "LY",
    dialCode: "+218",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Liechtenstein",
    flag: "li",
    code: "LI",
    dialCode: "+423",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Lithuania",
    flag: "lt",
    code: "LT",
    dialCode: "+370",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Luxembourg",
    flag: "lu",
    code: "LU",
    dialCode: "+352",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Macao",
    flag: "mo",
    code: "MO",
    dialCode: "+853",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Macedonia",
    flag: "mk",
    code: "MK",
    dialCode: "+389",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Madagascar",
    flag: "mg",
    code: "MG",
    dialCode: "+261",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Malawi",
    flag: "mw",
    code: "MW",
    dialCode: "+265",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "Malaysia",
    flag: "my",
    code: "MY",
    dialCode: "+60",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Maldives",
    flag: "mv",
    code: "MV",
    dialCode: "+960",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Mali",
    flag: "ml",
    code: "ML",
    dialCode: "+223",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Malta",
    flag: "mt",
    code: "MT",
    dialCode: "+356",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Marshall Islands",
    flag: "mh",
    code: "MH",
    dialCode: "+692",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Martinique",
    flag: "mq",
    code: "MQ",
    dialCode: "+596",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Mauritania",
    flag: "mr",
    code: "MR",
    dialCode: "+222",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Mauritius",
    flag: "mu",
    code: "MU",
    dialCode: "+230",
    minLength: 7,
    maxLength: 8,
  ),
  Country(
    name: "Mayotte",
    flag: "🇾🇹",
    code: "YT",
    dialCode: "+262",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Mexico",
    flag: "mx",
    code: "MX",
    dialCode: "+52",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Micronesia, Federated States of Micronesia",
    flag: "fm",
    code: "FM",
    dialCode: "+691",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Moldova",
    flag: "md",
    code: "MD",
    dialCode: "+373",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Monaco",
    flag: "mc",
    code: "MC",
    dialCode: "+377",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Mongolia",
    flag: "mn",
    code: "MN",
    dialCode: "+976",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Montenegro",
    flag: "me",
    code: "ME",
    dialCode: "+382",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Montserrat",
    flag: "ms",
    code: "MS",
    dialCode: "+1664",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Morocco",
    flag: "ma",
    code: "MA",
    dialCode: "+212",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Mozambique",
    flag: "mz",
    code: "MZ",
    dialCode: "+258",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Myanmar",
    flag: "mm",
    code: "MM",
    dialCode: "+95",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Namibia",
    flag: "na",
    code: "NA",
    dialCode: "+264",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Nauru",
    flag: "nr",
    code: "NR",
    dialCode: "+674",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Nepal",
    flag: "np",
    code: "NP",
    dialCode: "+977",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Netherlands",
    flag: "nl",
    code: "NL",
    dialCode: "+31",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Netherlands Antilles",
    flag: "",
    code: "AN",
    dialCode: "+599",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "New Caledonia",
    flag: "🇳🇨",
    code: "NC",
    dialCode: "+687",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "New Zealand",
    flag: "nz",
    code: "NZ",
    dialCode: "+64",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Nicaragua",
    flag: "ni",
    code: "NI",
    dialCode: "+505",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Niger",
    flag: "ne",
    code: "NE",
    dialCode: "+227",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Nigeria",
    flag: "ng",
    code: "NG",
    dialCode: "+234",
    minLength: 10,
    maxLength: 11,
  ),
  Country(
    name: "Niue",
    flag: "nu",
    code: "NU",
    dialCode: "+683",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: "Norfolk Island",
    flag: "nf",
    code: "NF",
    dialCode: "+672",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Northern Mariana Islands",
    flag: "mp",
    code: "MP",
    dialCode: "+1670",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Norway",
    flag: "no",
    code: "NO",
    dialCode: "+47",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Oman",
    flag: "om",
    code: "OM",
    dialCode: "+968",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Pakistan",
    flag: "pk",
    code: "PK",
    dialCode: "+92",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Palau",
    flag: "pw",
    code: "PW",
    dialCode: "+680",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Palestinian Territory, Occupied",
    flag: "ps",
    code: "PS",
    dialCode: "+970",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Panama",
    flag: "pa",
    code: "PA",
    dialCode: "+507",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Papua New Guinea",
    flag: "pg",
    code: "PG",
    dialCode: "+675",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Paraguay",
    flag: "py",
    code: "PY",
    dialCode: "+595",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Peru",
    flag: "pe",
    code: "PE",
    dialCode: "+51",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Philippines",
    flag: "ph",
    code: "PH",
    dialCode: "+63",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Pitcairn",
    flag: "pn",
    code: "PN",
    dialCode: "+64",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Poland",
    flag: "pl",
    code: "PL",
    dialCode: "+48",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Portugal",
    flag: "pt",
    code: "PT",
    dialCode: "+351",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Puerto Rico",
    flag: "pr",
    code: "PR",
    dialCode: "+1939",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Qatar",
    flag: "qa",
    code: "QA",
    dialCode: "+974",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Romania",
    flag: "ro",
    code: "RO",
    dialCode: "+40",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Russia",
    flag: "ru",
    code: "RU",
    dialCode: "+7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Rwanda",
    flag: "rw",
    code: "RW",
    dialCode: "+250",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Reunion",
    flag: "🇷🇪",
    code: "RE",
    dialCode: "+262",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Saint Barthelemy",
    flag: "🇧🇱",
    code: "BL",
    dialCode: "+590",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    code: "SH",
    dialCode: "+290",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: "Saint Kitts and Nevis",
    flag: "kn",
    code: "KN",
    dialCode: "+1869",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Saint Lucia",
    flag: "lc",
    code: "LC",
    dialCode: "+1758",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Saint Martin",
    flag: "🇲🇫",
    code: "MF",
    dialCode: "+590",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    code: "PM",
    dialCode: "+508",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Saint Vincent and the Grenadines",
    flag: "vc",
    code: "VC",
    dialCode: "+1784",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Samoa",
    flag: "ws",
    code: "WS",
    dialCode: "+685",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "San Marino",
    flag: "🇸🇲",
    code: "SM",
    dialCode: "+378",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Sao Tome and Principe",
    flag: "st",
    code: "ST",
    dialCode: "+239",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Saudi Arabia",
    flag: "sa",
    code: "SA",
    dialCode: "+966",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Senegal",
    flag: "sn",
    code: "SN",
    dialCode: "+221",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Serbia",
    flag: "rs",
    code: "RS",
    dialCode: "+381",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Seychelles",
    flag: "sc",
    code: "SC",
    dialCode: "+248",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Sierra Leone",
    flag: "sl",
    code: "SL",
    dialCode: "+232",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Singapore",
    flag: "sg",
    code: "SG",
    dialCode: "+65",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Slovakia",
    flag: "sk ",
    code: "SK",
    dialCode: "+421",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Slovenia",
    flag: "si",
    code: "SI",
    dialCode: "+386",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Solomon Islands",
    flag: "sb",
    code: "SB",
    dialCode: "+677",
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    name: "Somalia",
    flag: "so",
    code: "SO",
    dialCode: "+252",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "South Africa",
    flag: "za",
    code: "ZA",
    dialCode: "+27",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "South Sudan",
    flag: "ss",
    code: "SS",
    dialCode: "+211",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    code: "GS",
    dialCode: "+500",
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    name: "Spain",
    flag: "es",
    code: "ES",
    dialCode: "+34",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Sri Lanka",
    flag: "lk",
    code: "LK",
    dialCode: "+94",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Sudan",
    flag: "sd",
    code: "SD",
    dialCode: "+249",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Suriname",
    flag: "sr",
    code: "SR",
    dialCode: "+597",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    code: "SJ",
    dialCode: "+47",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Eswatini",
    flag: "🇸🇿",
    code: "SZ",
    dialCode: "+268",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Sweden",
    flag: "se",
    code: "SE",
    dialCode: "+46",
    minLength: 7,
    maxLength: 13,
  ),
  Country(
    name: "Switzerland",
    flag: "ch",
    code: "CH",
    dialCode: "+41",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Syrian Arab Republic",
    flag: "sy",
    code: "SY",
    dialCode: "+963",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Taiwan",
    flag: "tw",
    code: "TW",
    dialCode: "+886",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Tajikistan",
    flag: "tj",
    code: "TJ",
    dialCode: "+992",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Tanzania, United Republic of Tanzania",
    flag: "tz",
    code: "TZ",
    dialCode: "+255",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Thailand",
    flag: "th",
    code: "TH",
    dialCode: "+66",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Timor-Leste",
    flag: "tl",
    code: "TL",
    dialCode: "+670",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Togo",
    flag: "tg",
    code: "TG",
    dialCode: "+228",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Tokelau",
    flag: "tk",
    code: "TK",
    dialCode: "+690",
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    name: "Tonga",
    flag: "to",
    code: "TO",
    dialCode: "+676",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Trinidad and Tobago",
    flag: "tt",
    code: "TT",
    dialCode: "+1868",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Tunisia",
    flag: "tn",
    code: "TN",
    dialCode: "+216",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Turkey",
    flag: "tr",
    code: "TR",
    dialCode: "+90",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Turkmenistan",
    flag: "tm",
    code: "TM",
    dialCode: "+993",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Turks and Caicos Islands",
    flag: "tc",
    code: "TC",
    dialCode: "+1649",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Tuvalu",
    flag: "tv",
    code: "TV",
    dialCode: "+688",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Uganda",
    flag: "ug",
    code: "UG",
    dialCode: "+256",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Ukraine",
    flag: "ua",
    code: "UA",
    dialCode: "+380",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "United Arab Emirates",
    flag: "ae",
    code: "AE",
    dialCode: "+971",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "United Kingdom",
    flag: "gb",
    code: "GB",
    dialCode: "+44",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "United States",
    flag: "us",
    code: "US",
    dialCode: "+1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Uruguay",
    flag: "uy",
    code: "UY",
    dialCode: "+598",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Uzbekistan",
    flag: "uz",
    code: "UZ",
    dialCode: "+998",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Vanuatu",
    flag: "vu",
    code: "VU",
    dialCode: "+678",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "ve",
    code: "VE",
    dialCode: "+58",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Vietnam",
    flag: "vn",
    code: "VN",
    dialCode: "+84",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Virgin Islands, British",
    flag: "vg",
    code: "VG",
    dialCode: "+1284",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Virgin Islands, U.S.",
    flag: "🇻🇮",
    code: "VI",
    dialCode: "+1340",
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    name: "Wallis and Futuna",
    flag: "🇼🇫",
    code: "WF",
    dialCode: "+681",
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    name: "Yemen",
    flag: "ye",
    code: "YE",
    dialCode: "+967",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Zambia",
    flag: "🇿🇲",
    code: "ZM",
    dialCode: "+260",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Zimbabwe",
    flag: "zw",
    code: "ZW",
    dialCode: "+263",
    minLength: 9,
    maxLength: 9,
  ),
];


const defaultCountry =  Country(
  name: "Turkey",
  flag: "tr",
  code: "TR",
  dialCode: "+90",
  minLength: 11,
  maxLength: 11,
);

class Country {
  final String name;
  final String flag;
  final String code;
  final String dialCode;
  final String regionCode;
  final int minLength;
  final int maxLength;

  const Country({
    required this.name,
    required this.flag,
    required this.code,
    required this.dialCode,
    required this.minLength,
    required this.maxLength,
    this.regionCode = "",
  });

  String get fullCountryCode {
    return dialCode + regionCode;
  }

  String get displayCC {
    if (regionCode != "") {
      return "$dialCode $regionCode";
    }
    return dialCode;
  }

  @override
  String toString() {
    return 'Country{name: $name, flag: $flag, code: $code, dialCode: $dialCode, regionCode: $regionCode, minLength: $minLength, maxLength: $maxLength}';
  }
}