stages:
  - lint

lint:
  stage: lint
  script:
    - echo "Deploying to Firebase, AWS, etc..."
    - cd android  # Navigate to the android folder
    - bundle install  # Install Fastlane dependencies
    - fastlane android firebase_distribution  # 
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


