concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Android Fastlane with Firebase App Distribution Runner"
  url = "https://gitlab.com/"
  id = 45435591
  token = "glrt-t3_1YzfwwSB3i55VsFnE8Hd"
  token_obtained_at = 2025-01-19T11:25:21Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
