// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9kTZ9ai5KhGTlmJvnLlnf7C_Ws8WaO3c',
    appId: '1:1084769963721:web:2fb5a231dcc35c75620718',
    messagingSenderId: '1084769963721',
    projectId: 'cicd-cd171',
    authDomain: 'cicd-cd171.firebaseapp.com',
    storageBucket: 'cicd-cd171.firebasestorage.app',
    measurementId: 'G-1CV67E3P9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDowruPlck46c8_3bFUeDwZg6BgWvs9rBI',
    appId: '1:1084769963721:android:d7a1539abb20741b620718',
    messagingSenderId: '1084769963721',
    projectId: 'cicd-cd171',
    storageBucket: 'cicd-cd171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmy0j3cO7DOqfrkYl2qymhcKg2vRbfoqQ',
    appId: '1:1084769963721:ios:974063b512e181c0620718',
    messagingSenderId: '1084769963721',
    projectId: 'cicd-cd171',
    storageBucket: 'cicd-cd171.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmy0j3cO7DOqfrkYl2qymhcKg2vRbfoqQ',
    appId: '1:1084769963721:ios:974063b512e181c0620718',
    messagingSenderId: '1084769963721',
    projectId: 'cicd-cd171',
    storageBucket: 'cicd-cd171.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9kTZ9ai5KhGTlmJvnLlnf7C_Ws8WaO3c',
    appId: '1:1084769963721:web:212b6b83fbe5c812620718',
    messagingSenderId: '1084769963721',
    projectId: 'cicd-cd171',
    authDomain: 'cicd-cd171.firebaseapp.com',
    storageBucket: 'cicd-cd171.firebasestorage.app',
    measurementId: 'G-GM9ZR9ZY0V',
  );
}
